### ISSUE TITLE
swagger2openapi {host+scheme} -> {url} adds a slash that shouldn't be there

### ISSUE THREAD

**Issue by grantila** [Mermade/oas-kit#86] opened 2018-09-04 11:14 UTC
Upgrading from Swagger 2 to OpenAPI 3 (using swagger2openapi) converts {host, scheme} to a url with ending slash.

### Checklist

- [ ] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong
- [ ] Linting issue

When linting the resulting OpenAPI3 against `speccy` it complains about a trailing slash.

Probably the end of the line [index.js:1284](https://github.com/Mermade/oas-kit/blob/master/packages/swagger2openapi/index.js#L1284) should not else to `'/'` but `''`
This is also aligned with https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by MikeRalphson** [comment] 2018-09-06 14:33
As all `path` entries must start with a `/`, I can't see why having a `server.url` of `scheme://host` instead of `scheme://host/` makes any difference, as appending (say `/status`) will result in `scheme://host/status` in either case.

I'm not convinced speccy's rule `server-trailing-slash` is **necessarily** something I'd want to enforce personally. Pinging @philsturgeon

**Comment by philsturgeon** [comment] 2018-09-06 18:01
This is an opinion that I/speccy has, not a bug in oas-kit. 

The oopinion is based around certain tools double slashing, when the server and path both contain a slash. Some strip the double slash, done don’t.

**Comment by philsturgeon** [comment] 2018-09-06 18:06
Sorry typing this message on a mobile from Vegas so typos.

**Comment by MikeRalphson** [comment] 2018-09-21 10:36
I think it comes down to this line in [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#patterned-fields):

> A relative path to an individual endpoint. The field name MUST begin with a slash. The path is **appended** (no relative URL resolution) to the expanded URL from the Server Object's url field in order to construct the full URL.

So I'm going to make the change as you suggested. Thanks again.

**Comment by MikeRalphson** [comment] 2018-09-21 11:27
Fixed in swagger2openapi@3.2.9

**Closed by MikeRalphson** 2018-09-21 11:27 UTC
