### ISSUE TITLE
YAML anchors/aliases can confuse converter

### ISSUE THREAD

**Issue by rtfpessoa** [Mermade/oas-kit#217] opened 2020-03-23 23:24 UTC
### Checklist

- [X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

When converting a valid v2 to v3 I get an error saying `(Patchable) parameter.type is mandatory for non-body parameters`.
After some debugging, seems like the raw spec of the parameters is converted to json schema and instead of having a `.type` property the parameter object has a `.schema.type` instead.

#### Other stuff

Using latest version

Any ideas what can be wrong?

**Comment by MikeRalphson** [comment] 2020-03-24 07:37
The error message relates to the input definition, so it is likely there is a parameter without a `type` set (or there is a bug).

There's three things you can do:
* Find and fix the missing `type`
* Add the `--patch` option or set `options.patch` which will fix it for you by assuming the parameter is of `type: string`
* Link your input definition here so I can take a look.

**Comment by rtfpessoa** [comment] 2020-03-24 08:54
@MikeRalphson thank you for the quick response.
I would really like to avoid the patch since my api should be fully valid. And I cannot find the missing type. It passes the suggested validator you suggested and the swagger online one.

Here is the minimal example where I could replicate the issue:

```
swagger: '2.0'
info:
  version: 1.0.0
  title: 'My API'
  description: 'My API'
  termsOfService: 'https://hello.world/terms/'
  contact:
    name: 'My API Owner'
    email: myapi@example.com
    url: 'https://www.example.com'
  license:
    name: 'My API. All rights reserved'
    url: 'https://www.example.com'

tags:
  - name: example
    description: 'example endpoints'

schemes:
  - http

host: example.com

basePath: /v1

produces:
  - application/json
consumes:
  - application/json

parameters:
  tokenParam: &tokenParam
    in: header
    name: token
    description: 'Token'
    required: false
    type: string

paths:
  '/example':
    get:
      tags:
        - example
      summary: 'Get example'
      description: 'Get example'
      operationId: getExample
      parameters:
        - *tokenParam
      responses:
        '200':
          description: 'Successful operation'
          schema:
            $ref: "#/definitions/ExampleResponse"

definitions:
  ExampleResponse:
    type: object
    required:
      - description
    properties:
      description:
        type: string
```

**Comment by MikeRalphson** [comment] 2020-03-24 09:16
The problem is (probably) two-fold.

You are using features of YAML (anchors and references) which are not representable in JSON. This is contrary to the OpenAPI specification which mandates this for interoperability.

The correct way to reference a shared parameter would be as follows:

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'My API'
  description: 'My API'
  termsOfService: 'https://hello.world/terms/'
  contact:
    name: 'My API Owner'
    email: myapi@example.com
    url: 'https://www.example.com'
  license:
    name: 'My API. All rights reserved'
    url: 'https://www.example.com'

tags:
  - name: example
    description: 'example endpoints'

schemes:
  - http

host: example.com

basePath: /v1

produces:
  - application/json
consumes:
  - application/json

parameters:
  tokenParam:
    in: header
    name: token
    description: 'Token'
    required: false
    type: string

paths:
  '/example':
    get:
      tags:
        - example
      summary: 'Get example'
      description: 'Get example'
      operationId: getExample
      parameters:
        - $ref: '#/parameters/tokenParam'
      responses:
        '200':
          description: 'Successful operation'
          schema:
            $ref: "#/definitions/ExampleResponse"

definitions:
  ExampleResponse:
    type: object
    required:
      - description
    properties:
      description:
        type: string
```

I.e. using a JSON-Reference not a YAML anchor.

The cause of the issue is that in your original example, both of the instances of the `tokenParam` are actually references to the same in-memory object. What I think is happening is that the shared parameter is getting converted, but then the second reference to it gets converted **a second time**, when the `type` property has already been moved to `schema.type`.

I will look at fixing the behaviour so no-one else gets caught out by this (either by checking for shared objects or detecting already converted parameters) but you should really change the way you reference the parameter in your source definition.

**Comment by rtfpessoa** [comment] 2020-03-24 12:37
@MikeRalphson I understand your idea and we definitely should not use anchors for this use case but due to limitations in one tool we are using it is needed.

What bugs me is why doesn't the yaml parser handle this correctly.
It works fine with the official swagger parser.

If you have any pointers or suggestions on the fix I can help.

**Comment by MikeRalphson** [comment] 2020-03-24 13:11
The yaml parser is handling it correctly and doing exactly what you're telling it to do (link the two objects in memory so they point to the same thing).

It **is** the `swagger2openapi` converter which is tripping up, but as above, the anchor/alias should not be there as per the OAS spec.

There's a temporary workaround: put your definition through something which de-references the yaml anchors, such as converting it to JSON (and back again if needed).

I should have a fix soon (you might need to use a new option to bypass the new check for anchors/aliases).

**Comment by MikeRalphson** [comment] 2020-03-24 14:33
Should be fixed in `swagger2openapi v6.0.0`. You will need to pass in the `--anchors` option or set `options.anchors` to `true`. Thanks for flagging this up.

**Comment by rtfpessoa** [comment] 2020-03-27 19:57
@MikeRalphson thanks a lot, it works great.

**Comment by rtfpessoa** [comment] 2020-04-01 20:42
@MikeRalphson Just noticed a weird behaviour.
Seems like the destination were an object is being unrolled stays with an extra wrapper called `<<`.

e.g.:

// What happens
```
      "ObjectListItem": {
        "<<": {
          "type": "object",
          "required": ["name"],
          "properties": {
            "name": { "type": "string" }
          }
        },
        "required": ["name"]
      },
```

// What should happen
```
      "ObjectListItem": {
        "type": "object",
        "required": ["name"],
        "properties": {
          "name": { "type": "string" }
        }
      }
```

Any ideas?

**Comment by MikeRalphson** [comment] 2020-04-02 06:27
I'm a bit confused because your examples are in JSON, but I guess your input is still in YAML?

YAML merge keys `<<` are a feature of YAML 1.1 which was dropped in YAML 1.2. To enable YAML merge key support, please add a `%YAML 1.1` directive to the top of your input file. This is another feature of YAML which is not directly permitted by the OpenAPI spec.

Let me know if this does/doesn't resolve your issue.

**Comment by rtfpessoa** [comment] 2020-04-02 21:09
@MikeRalphson I was not aware of that. Seems like that fixes the problem.

Do you know if there is a similar feature for yaml 1.2 where I can have all the same properties from an object but override one? (mostly for the sake of re-usability)

**Comment by MikeRalphson** [comment] 2020-04-13 14:36
No, unfortunately there is not (as far as I know) any similar functionality in YAML 1.2

**Closed by MikeRalphson** 2020-04-13 14:36 UTC
