### ISSUE TITLE
Is it possible to not throw error if corresponding $ref could not be resolved in oas-resolver.

### ISSUE THREAD

**Issue by VShingala** [Mermade/oas-kit#282] opened 2020-09-17 20:36 UTC
### Checklist

- [ ] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong
- [ ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain
- [ ] Linting issue
- [x] Resolver issue

### Detailed Description
While using oas-resolver I could not found a way to not throw the error if `$ref` could not be resolved. Is there any way to achieve this use case where correctly defined `$ref` will be resolved and wrong `$ref` will be present in the result as is instead throwing error.

### Other stuff
Using oas-resolver@2.3.3

**Comment by MikeRalphson** [comment] 2020-09-17 21:00
Are you setting `options.fatal` to `true`?

**Comment by VShingala** [comment] 2020-09-17 21:16
I tried with both `true` and `false` for option `fatal` but the `$ref` that's incorrect always throws an error.

**Comment by MikeRalphson** [comment] 2020-09-18 07:05
Interesting, can you share your definition in a gist or link?

**Comment by VShingala** [comment] 2020-09-18 07:39
Sure, Here is OpenAPI [definition](https://raw.githubusercontent.com/VShingala/api-schema/master/resolver-issue.yaml), and below is how I am using `oas-resolver@2.3.3`.

```
// openapi is definition
resolver.resolve(openapi, sourceUrl, {
        resolve: true,
        externals: [],
        externalRefs: {},
        openapi: openapi,
        fatal: true
      })
        .then(function(result) {
          // handling
        })
        .catch(function(err) {
          // error handling
        });
```

Now in the above code, when `sourceUrl` is correct i.e. `https://raw.githubusercontent.com/VShingala/api-schema/master/resolver-issue.yaml` it will resolve the definition correctly but when it's empty `''` it will throw an error instead of just not resolving it and keeping it as is.

**Comment by MikeRalphson** [comment] 2020-09-18 07:49
I'm not sure why you're calling `resolve` at all if you don't have a `source`. It's a mandatory part of the resolving process. The `source` can also be a local filepath or `file://` url.

**Comment by VShingala** [comment] 2020-09-18 07:58
Sorry if the mentioned example didn't make sense.

I have a source that is correct and correctly resolves defined refs from the definition, but only one incorrect ref present in the definition shouldn't stop all correctly defined refs from getting resolved that's the problem.

**Comment by MikeRalphson** [comment] 2020-09-18 08:08
The problem is that resolving is a recursive process. New external `$ref`s may appear as a result of resolving another `$ref`. The code would need to be changed to keep track of all failing `$ref`s so as not to keep trying endlessly. This would need to be done in a way which did not hurt performance.

I will take a look.

**Comment by MikeRalphson** [comment] 2020-09-18 08:27
Could you amend your example so it has one broken `$ref` where `oas-resolver` throws an exception when `options.fatal` is `false`? Let's fix that first.

**Comment by MikeRalphson** [comment] 2020-09-18 10:48
Could you try `oas-resolver@2.5.0` ? You will need to set `options.ignoreIOErrors` true for your use case. The `options.externalRefs` map entries will have a `failed` property set `true` for unresolveable `$ref`s.

**Comment by VShingala** [comment] 2020-09-21 13:25
@MikeRalphson Thanks for such a quick response!

I have verified the option `ignoreIOErrors` on `oas-resolver@2.5.0` and is working as expected for my use case.

**Comment by MikeRalphson** [comment] 2020-09-21 20:10
Many thanks for confirming.

**Closed by MikeRalphson** 2020-09-21 20:10 UTC
